---
- name: Install, enable, and start PostgreSQL
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: install postgres
      ansible.builtin.dnf:
        name: postgresql-server
        state: present
    - name: enable postgres
      ansible-builtin.systemd_service:
        name: postgresql
        state: started
        enabled: true
    - name: open firewall ports for postgres
      ansible.builtin.firewalld:
        service: postgresql
        state: enabled
        permanent: true
        immediate: true
